services:
  postgres:
    image: postgres:15-alpine
    container_name: resq-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: resq
      POSTGRES_USER: resq
      POSTGRES_PASSWORD: resq
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: resq-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  livekit:
    image: livekit/livekit-server:latest
    container_name: resq-livekit
    ports:
      - "7880:7880"
      - "7881:7881"
    restart: unless-stopped
    command: --config /etc/livekit/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit/livekit.yaml
      - livekit_data:/var/lib/livekit

volumes:
  postgres_data:
  redis_data:
  livekit_data:
