services:
  redis:
    image: redis:7-alpine
    container_name: resq-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  livekit:
    image: livekit/livekit-server:latest
    container_name: resq-livekit
    ports:
      - "7880:7880"
      - "7881:7881"
    restart: unless-stopped
    command: --config /etc/livekit/livekit.yaml
    volumes:
      - ./livekit.yaml:/etc/livekit/livekit.yaml
      - livekit_data:/var/lib/livekit

volumes:
  redis_data:
  livekit_data:
